services:
  - type: web
    name: salon-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false 